[cache]
dir = "~/.cache/tlrc"
mirror = "https://github.com/tldr-pages/tldr/releases/latest/download"
auto_update = true
max_age = 336
languages = []

[output]
show_title = true
platform_title = false
show_hyphens = false
example_prefix = "- "
compact = false
raw_markdown = false

[indent]
title = 2
description = 2
bullet = 2
example = 4

[style.title]
color = { rgb = [162, 70, 190] } # Pink
background = { rgb = [16, 16, 16] }
bold = true
underline = false
italic = false
dim = false
strikethrough = false

[style.description]
color = { rgb = [151, 197, 2] } # Green
background = { rgb = [16, 16, 16] }
bold = false
underline = false
italic = false
dim = false
strikethrough = false

[style.bullet]
color = { rgb = [2, 199, 151] } # noraj (main)
background = { rgb = [16, 16, 16] }
bold = false
underline = false
italic = false
dim = false
strikethrough = false

[style.example]
color = { rgb = [70, 158, 190] } # Blue
background = { rgb = [16, 16, 16] }
bold = false
underline = false
italic = false
dim = false
strikethrough = false

[style.url]
color = { rgb = [190, 100, 70] } # Orange
background = { rgb = [16, 16, 16] }
bold = false
underline = false
italic = true
dim = false
strikethrough = false

[style.inline_code]
color = { rgb = [197, 187, 2] } # Yellow
background = { rgb = [16, 16, 16] }
bold = false
underline = false
italic = true
dim = false
strikethrough = false

[style.placeholder]
color = { rgb = [197, 2, 51] } # Red
background = { rgb = [16, 16, 16] }
bold = false
underline = false
italic = true
dim = false
strikethrough = false
